<?php
return [
    'site_title' => 'IL DIVANO D\'ORO',
    'home' => 'Home',
    'results' => 'Results',
    'all_votes' => 'All Votes',
    'logout' => 'Logout',
    'login' => 'Login',
    'register' => 'Register',
    'hello' => 'Hello',
    'download_excel' => 'Download Excel',
    'view_my_votes' => 'View My Votes',
    'profile' => 'Profile',
    'submit_vote' => 'Submit Vote',
    'cancel' => 'Cancel',
    'language' => 'Language',
    'lang_en' => 'EN',
    'lang_it' => 'IT',
    'email' => 'Email',
    'password' => 'Password',
    'email_placeholder' => 'you@example.com',
    'password_placeholder' => '••••••••',
    'create_account' => 'Create account',
    'invalid_credentials' => 'Invalid email or password',
    'forgot_password' => 'Forgot Password?',
    'footer_text' => '© IL DIVANO D\'ORO — All rights reserved.',
    'username' => 'Username',
    'username_placeholder' => 'Choose a username',
    'already_have_account' => 'Already have an account?',
    'all_competitions' => 'All competitions',
    'total' => 'Total',
    'unique_titles' => 'Unique Titles',
    'total_views' => 'Total Views',
    'platform' => 'Platform',
    'qualitative_average' => 'Qualitative Average',
    'titles' => 'Titles',
    'average_rating' => 'Average Rating',
    'best_of' => 'Best Of',
    'most_viewed' => 'Most Viewed',
    'jurors' => 'Jurors',
    'stats_compact_title' => 'Highlights',
    'no_data_yet' => 'No data for this year yet.',
    'finalists' => 'Finalists',
    'judge' => 'Judge',
    'avg_total' => 'Average Total',
    'avg_writing' => 'Average Writing',
    'avg_direction' => 'Average Direction',
    'avg_acting_theme' => 'Average Acting / Theme',
    'avg_emotional' => 'Average Emotional Involvement',
    'avg_novelty' => 'Average Sense of Novelty',
    'avg_casting_artwork' => 'Average Casting / Artwork',
    'avg_sound' => 'Average Sound',
    'count_10s' => 'Count of 10s',
    'percent_10s' => '% of 10s',
    'adjectives' => 'Adjectives',
    'views' => 'Views',
    'view' => 'View',
    'all_fields_required' => 'All fields are required',
    'username_email_exists' => 'Username or email already exists',
    'search_movies' => 'Search title...',
    'search' => 'Search',
    'searching' => 'Searching',
    'search_intro' => 'Find a movie you want to vote on.',
    'search_no_results' => 'No movies matched your search. Try a different title.',
    'vote' => 'Vote',
    'vote' => 'Vote',
    'stats' => 'Stats',
    'my_votes' => 'My Votes',
    'votes' => 'Votes',
    'my_profile' => 'My Profile',
    'edit_profile' => 'Edit Profile',
    'save_changes' => 'Save Changes',
    'total_votes' => 'Total Votes',
    'movies_voted' => 'movie(s) voted',
    'profile_updated' => 'Profile updated successfully!',
    'error_updating_profile' => 'Error updating profile',
    'your_votes' => 'Your Votes',
    'your_votes_detailed' => 'Your Votes (detailed)',
    'your_profile' => 'Your Profile',
    'watchlist' => 'Watchlist',
    'your_ratings' => 'Your Ratings',
    'account_settings' => 'Account Settings',
    'sign_out' => 'Sign Out',
    'your_saved_movies' => 'Your saved movies to watch',
    'movies' => 'Movies',
    'watchlist_empty' => 'Your watchlist is empty',
    'watchlist_empty_desc' => 'Start adding movies you want to watch later',
    'browse_movies' => 'Browse Movies',
    'remove_from_watchlist_confirm' => 'Remove this movie from your watchlist?',
    'add_to_watchlist' => 'Add to Watchlist',
    'movie' => 'Movie',
    'year' => 'Year',
    'select_year' => 'Select year',
    'select_competition_status' => 'Filter by status',
    'all_status' => 'All',
    'filter_in_competition' => 'In Competition',
    'filter_out_of_competition' => 'Out of Competition',
    'status_detail_in_2025' => 'IN COMPETITION (within the active window)',
    'status_detail_in_2026' => 'IN COMPETITION (within the active window)',
    'status_detail_out' => 'OUT OF COMPETITION (outside the active window)',
    'status_detail_all' => 'All votes regardless of competition status',
    'your_rating' => 'Your Rating',
    'when' => 'When',
    'computed_rating' => 'Average',
    'actions' => 'Actions',
    'edit' => 'Edit',
    'celebrating_cinema' => 'Celebrating Cinema Together',
    'official_voting_form' => 'Official Voting Form',
    'competition_status' => 'Competition Status',
    'required' => '*',
    'in_competition' => 'In Competition',
    'out_of_competition' => 'Out of Competition',
    'badge_in_competition' => 'In competition',
    'badge_out_of_competition' => 'Out of competition',
    'category' => 'Category',
    'choose' => 'Choose...',
    'film' => 'Film',
    'series' => 'Series',
    'miniseries' => 'Miniseries',
    'documentary' => 'Documentary',
    'animation' => 'Animation',
    'where_watched' => 'Where did you watch it?',
    'cinema' => 'Cinema',
    'writing' => 'Writing',
    'direction' => 'Direction',
    'acting_theme' => 'Acting / Theme Choice (documentaries)',
    'emotional_involvement' => 'Emotional Involvement',
    'novelty' => 'Sense of Novelty',
    'casting_research' => 'Casting / Research (documentaries) / Character Artwork (animation)',
    'sound' => 'Sound',
    'vote_1_to_10' => 'Vote from 1 to 10 (half points allowed)',
    'adjective' => 'Describe what you just watched with one adjective',
    'adjective_placeholder' => 'e.g., Captivating, Boring, Inspiring...',
    'adjective_helper' => 'Optional: One word that summarizes your experience',
    // Column headers for vote details
    'acting_or_doc_theme' => 'Acting / Theme',
    'casting_research_art' => 'Casting / Research / Artwork',
    'vote_id' => 'Vote ID',
    'release_year' => 'Release Year',
    'in_competition_section' => 'In Competition',
    // Sheets / tabs
    'sheet_votes' => 'Votes {year}',
    'sheet_results' => 'Results {year}',
    'sheet_views' => 'Views {year}',
    'sheet_judges' => 'Judges',
    'sheet_judges_comp' => 'Judges – Competition Only',
    'sheet_titles' => 'Title List',
    'sheet_adjectives' => 'Adjective List',
    'sheet_finalists_2023' => 'Finalists',
    'raw_votes' => 'Raw Votes',
    'top_voted' => 'Top Voted on Divano d\'Oro',
    'imdb_top_week_note' => 'Top 10 in competition from IMDb this week'
    , 'in_theatres' => 'In Theatres'
    , 'recently_added' => 'Recently Added'
    , 'season' => 'Season'
    , 'episode' => 'Episode'
    , 'season_number' => 'Season'
    , 'episode_number' => 'Episode'
    , 'season_placeholder' => 'Season #'
    , 'episode_placeholder' => 'Episode #'
    , 'season_episode' => 'Season'
    , 'season_episode_helper' => 'For series/miniseries, enter the season you are rating (episodes not needed).'
    , 'movie_results' => 'Movie Results'
    , 'raw_votes' => 'All Votes (raw)'
    , 'sheet_movies' => 'Results'
    , 'sheet_raw' => 'Votes'
    , 'already_voted_title' => "You've Already Voted"
    , 'already_voted_message' => 'You have already submitted a vote for %s in this competition.'
    , 'already_voted_hint' => 'You can edit your vote until the competition ends.'
    , 'edit_vote' => 'Edit Vote'
    , 'back' => 'Back'
    , 'back_to_list' => 'Back to list'
    , 'vote_details' => 'Vote Details'
    , 'juror' => 'Juror'
    , 'overall_rating' => 'Overall Rating'
    , 'no_votes_yet' => 'No votes yet'
    , 'no_results_found' => 'No results found for this category'
    , 'documentaries' => 'Documentaries'
    , 'voted_titles' => 'Voted Titles'
    , 'create_set_next_year' => 'Create & set next year'
    , 'start_competition_flow' => 'New competition'
    , 'competition_name_label' => 'Name'
    , 'competition_start_label' => 'Start'
    , 'competition_end_label' => 'End'
    , 'create_competition_action' => 'Create competition'
    , 'competition_placeholder' => 'Competition'
    , 'active_badge' => 'Active'
    , 'set_active_competition' => 'Set active competition'
];
