<?php
return [
    'site_title' => 'IL DIVANO D\'ORO',
    'home' => 'Home',
    'results' => 'Risultati',
    'all_votes' => 'Tutti i Voti',
    'logout' => 'Esci',
    'login' => 'Accedi',
    'register' => 'Registrati',
    'hello' => 'Ciao',
    'all_competitions' => 'Tutte le competizioni',
    'total' => 'Totale',
    'unique_titles' => 'Titoli Unici',
    'total_views' => 'Totale Visioni',
    'platform' => 'Piattaforma',
    'qualitative_average' => 'Media Qualitativa',
    'titles' => 'Titoli',
    'average_rating' => 'Media Voto',
    'best_of' => 'Il meglio',
    'most_viewed' => 'Più visti',
    'jurors' => 'Giurati',
    'stats_compact_title' => 'Panoramica',
    'no_data_yet' => 'Nessun dato per quest\'anno.',
    'finalists' => 'Finalisti',
    'judge' => 'Giudice',
    'avg_total' => 'Media Tot Votazioni',
    'avg_writing' => 'Media Sceneggiatura',
    'avg_direction' => 'Media Regia',
    'avg_acting_theme' => 'Media Recitazione/Tema',
    'avg_emotional' => 'Media Coinvolgimento',
    'avg_novelty' => 'Media Senso di Novità',
    'avg_casting_artwork' => 'Media Casting/Artwork',
    'avg_sound' => 'Media Sonoro',
    'count_10s' => 'Quanti 10',
    'percent_10s' => '% di 10',
    'adjectives' => 'Aggettivi',
    'views' => 'Visioni',
    'view' => 'Vedi',
    'download_excel' => 'Scarica Excel',
    'view_my_votes' => 'Vedi i miei voti',
    'profile' => 'Profilo',
    'submit_vote' => 'Invia Voto',
    'cancel' => 'Annulla',
    'language' => 'Lingua',
    'lang_en' => 'EN',
    'lang_it' => 'IT',
    'email' => 'Email',
    'password' => 'Password',
    'email_placeholder' => 'tu@esempio.com',
    'password_placeholder' => '••••••••',
    'create_account' => 'Crea account',
    'invalid_credentials' => 'Email o password non validi',
    'forgot_password' => 'Password dimenticata?',
    'footer_text' => '© IL DIVANO D\'ORO 2025 — Tutti i diritti riservati.',
    'username' => 'Nome utente',
    'username_placeholder' => 'Scegli un nome utente',
    'already_have_account' => 'Hai già un account?',
    'all_fields_required' => 'Tutti i campi sono obbligatori',
    'username_email_exists' => 'Nome utente o email già esistente',
    'search_movies' => 'Cerca titolo...',
    'search' => 'Cerca',
    'searching' => 'Ricerca in corso',
    'search_intro' => 'Cerca un titolo da votare.',
    'search_no_results' => 'Nessun film trovato per questa ricerca. Prova con un altro titolo.',
    'rate' => 'Vota',
    'vote' => 'Vota',
    'stats' => 'Statistiche',
    'my_votes' => 'I miei voti',
    'votes' => 'Voti',
    'my_profile' => 'Il mio profilo',
    'edit_profile' => 'Modifica profilo',
    'save_changes' => 'Salva modifiche',
    'total_votes' => 'Voti totali',
    'movies_rated' => 'film votati',
    'profile_updated' => 'Profilo aggiornato con successo!',
    'error_updating_profile' => 'Errore nell\'aggiornamento del profilo',
    'your_votes' => 'I tuoi voti',
    'your_votes_detailed' => 'I tuoi voti (dettagliati)',
    'your_profile' => 'Il Tuo Profilo',
    'watchlist' => 'Lista da Vedere',
    'your_ratings' => 'I Tuoi Voti',
    'account_settings' => 'Impostazioni Account',
    'sign_out' => 'Esci',
    'your_saved_movies' => 'I tuoi film salvati da guardare',
    'movies' => 'Film',
    'watchlist_empty' => 'La tua lista è vuota',
    'watchlist_empty_desc' => 'Inizia ad aggiungere film che vuoi guardare più tardi',
    'browse_movies' => 'Sfoglia Film',
    'remove_from_watchlist_confirm' => 'Rimuovere questo film dalla tua lista?',
    'add_to_watchlist' => 'Aggiungi alla Lista',
    'movie' => 'Film',
    'year' => 'Anno',
    'select_year' => 'Seleziona anno',
    'your_rating' => 'Il tuo voto',
    'when' => 'Quando',
    'computed_rating' => 'Media',
    'actions' => 'Azioni',
    'edit' => 'Modifica',
    'celebrating_cinema' => 'Celebrando il Cinema Insieme',
    'official_voting_form' => 'Modulo di Voto Ufficiale',
    'competition_status' => 'Stato della competizione',
    'required' => '*',
    'in_competition' => 'In Competizione (19 Dic 2024 - 31 Ott 2025)',
    '2026_in_competition' => '2026 In Competizione (1 Nov 2025 - fine 2026)',
    'out_of_competition' => 'Fuori Competizione (18 Dic 2024 e precedenti)',
    'badge_in_competition' => 'In competizione',
    'badge_out_of_competition' => 'Fuori competizione',
    'category' => 'Categoria',
    'choose' => 'Scegli...',
    'film' => 'Film',
    'series' => 'Serie',
    'miniseries' => 'Miniserie',
    'documentary' => 'Documentario',
    'animation' => 'Animazione',
    'where_watched' => 'Dove l\'hai guardato?',
    'cinema' => 'Cinema',
    'writing' => 'Scrittura',
    'direction' => 'Regia',
    'acting_theme' => 'Recitazione / Scelta del tema (documentari)',
    'emotional_involvement' => 'Coinvolgimento emotivo',
    'novelty' => 'Senso di nuovo',
    'casting_research' => 'Casting / Ricerca (documentari) / Design personaggi (animazione)',
    'sound' => 'Sonoro',
    'rate_1_to_10' => 'Vota da 1 a 10 (mezzi punti consentiti)',
    'adjective' => 'Descrivi ciò che hai appena visto con un aggettivo',
    'adjective_placeholder' => 'es. Avvincente, Noioso, Ispirante...',
    'adjective_helper' => 'Facoltativo: Una parola che riassume la tua esperienza',
    // Column headers for vote details
    'acting_or_doc_theme' => 'Recitazione / Tema',
    'casting_research_art' => 'Casting / Ricerca / Artwork',
    'vote_id' => 'ID Voto',
    'release_year' => 'Anno di uscita'
    , 'in_competition_section' => 'In Competizione'
    , 'top_rated' => 'Più votati'
    , 'in_theatres' => 'Al Cinema'
    , 'recently_added' => 'Aggiunti di recente'
    , 'season' => 'Stagione'
    , 'episode' => 'Episodio'
    , 'season_number' => 'Stagione'
    , 'episode_number' => 'Episodio'
    , 'season_placeholder' => 'Stagione #'
    , 'episode_placeholder' => 'Episodio #'
    , 'season_episode' => 'Stagione'
    , 'season_episode_helper' => 'Per serie/miniserie indica solo la stagione che stai valutando (episodi non necessari).'
    , 'movie_results' => 'Risultati Film'
    , 'raw_votes' => 'Tutti i voti (grezzi)'
    , 'sheet_movies' => 'Risultati 2024'
    , 'sheet_raw' => 'Voti 2024'
    , 'sheet_votes' => 'Votazioni {year}'
    , 'sheet_results' => 'Risultati {year}'
    , 'sheet_views' => 'Visioni {year}'
    , 'sheet_judges' => 'Giudici'
    , 'sheet_judges_comp' => 'Giudici – Solo Concorso'
    , 'sheet_titles' => 'Elenco Titoli'
    , 'sheet_adjectives' => 'Elenco Aggettivi'
    , 'sheet_finalists_2023' => 'Finalisti 2023'
    , 'already_voted_title' => 'Hai già votato'
    , 'already_voted_message' => 'Hai già inviato un voto per %s in questa competizione.'
    , 'already_voted_hint' => 'Puoi modificare il tuo voto finché la competizione non termina.'
    , 'edit_vote' => 'Modifica voto'
    , 'back' => 'Indietro'
    , 'back_to_list' => 'Torna alla lista'
    , 'vote_details' => 'Dettagli Voti'
    , 'juror' => 'Giurato'
    , 'overall_rating' => 'Voto Complessivo'
    , 'no_votes_yet' => 'Nessun voto ancora'
    , 'no_results_found' => 'Nessun risultato trovato per questa categoria'
    , 'documentaries' => 'Documentari'
    , 'voted_titles' => 'Titoli Votati'
];
